package hu.bme.aut.it9p0z.fixkin.util

import android.os.Build
import androidx.annotation.RequiresApi
import hu.bme.aut.it9p0z.fixkin.data.model.ConditionLog
import java.time.LocalDateTime

@RequiresApi(Build.VERSION_CODES.O)
val conditionMockLogs = listOf<ConditionLog>(
    ConditionLog(
        date = LocalDateTime.of(2022, 5, 1, 5, 10),
        feeling = ConditionLog.Feeling.feeling_1,
        food_trigger_1 = 1,
        food_trigger_2 = 0,
        food_trigger_3 = 0,
        food_trigger_4 = 1,
        food_trigger_5 = 0,
        food_trigger_6 = 0,
        food_trigger_7 = 1,
        food_trigger_8 = 0,
        food_trigger_9 = 0,
        food_trigger_10 = 0,
        weather_trigger_1 = 1,
        weather_trigger_2 = 0,
        weather_trigger_3 = 0,
        weather_trigger_4 = 0,
        weather_trigger_5 = 1,
        weather_trigger_6 = 0,
        weather_trigger_7 = 1,
        weather_trigger_8 = 1,
        mental_health_trigger_1 = 1,
        mental_health_trigger_2 = 0,
        mental_health_trigger_3 = 1,
        other_trigger_1 = 0,
        other_trigger_2 = 0,
        other_trigger_3 = 0,
        other_trigger_4 = 0
    ),
    ConditionLog(
        date = LocalDateTime.of(2022, 5, 3, 6, 15),
        feeling = ConditionLog.Feeling.feeling_1,
        food_trigger_1 = 1,
        food_trigger_2 = 0,
        food_trigger_3 = 1,
        food_trigger_4 = 0,
        food_trigger_5 = 0,
        food_trigger_6 = 0,
        food_trigger_7 = 1,
        food_trigger_8 = 1,
        food_trigger_9 = 1,
        food_trigger_10 = 0,
        weather_trigger_1 = 1,
        weather_trigger_2 = 0,
        weather_trigger_3 = 0,
        weather_trigger_4 = 0,
        weather_trigger_5 = 1,
        weather_trigger_6 = 0,
        weather_trigger_7 = 1,
        weather_trigger_8 = 1,
        mental_health_trigger_1 = 1,
        mental_health_trigger_2 = 0,
        mental_health_trigger_3 = 1,
        other_trigger_1 = 0,
        other_trigger_2 = 0,
        other_trigger_3 = 1,
        other_trigger_4 = 0
    ),
    ConditionLog(
        date = LocalDateTime.of(2022, 5, 6, 4, 0),
        feeling = ConditionLog.Feeling.feeling_1,
        food_trigger_1 = 1,
        food_trigger_2 = 0,
        food_trigger_3 = 0,
        food_trigger_4 = 1,
        food_trigger_5 = 0,
        food_trigger_6 = 1,
        food_trigger_7 = 1,
        food_trigger_8 = 0,
        food_trigger_9 = 0,
        food_trigger_10 = 0,
        weather_trigger_1 = 1,
        weather_trigger_2 = 0,
        weather_trigger_3 = 1,
        weather_trigger_4 = 0,
        weather_trigger_5 = 1,
        weather_trigger_6 = 0,
        weather_trigger_7 = 1,
        weather_trigger_8 = 1,
        mental_health_trigger_1 = 1,
        mental_health_trigger_2 = 0,
        mental_health_trigger_3 = 1,
        other_trigger_1 = 0,
        other_trigger_2 = 0,
        other_trigger_3 = 1,
        other_trigger_4 = 0
    ),
    ConditionLog(
        date = LocalDateTime.of(2022, 5, 7, 9, 10),
        feeling = ConditionLog.Feeling.feeling_2,
        food_trigger_1 = 1,
        food_trigger_2 = 0,
        food_trigger_3 = 0,
        food_trigger_4 = 1,
        food_trigger_5 = 0,
        food_trigger_6 = 0,
        food_trigger_7 = 1,
        food_trigger_8 = 0,
        food_trigger_9 = 0,
        food_trigger_10 = 0,
        weather_trigger_1 = 1,
        weather_trigger_2 = 0,
        weather_trigger_3 = 0,
        weather_trigger_4 = 0,
        weather_trigger_5 = 0,
        weather_trigger_6 = 1,
        weather_trigger_7 = 1,
        weather_trigger_8 = 0,
        mental_health_trigger_1 = 0,
        mental_health_trigger_2 = 1,
        mental_health_trigger_3 = 1,
        other_trigger_1 = 0,
        other_trigger_2 = 1,
        other_trigger_3 = 0,
        other_trigger_4 = 0
    ),
    ConditionLog(
        date = LocalDateTime.of(2022, 5, 9, 5, 10),
        feeling = ConditionLog.Feeling.feeling_3,
        food_trigger_1 = 1,
        food_trigger_2 = 0,
        food_trigger_3 = 1,
        food_trigger_4 = 1,
        food_trigger_5 = 0,
        food_trigger_6 = 0,
        food_trigger_7 = 1,
        food_trigger_8 = 0,
        food_trigger_9 = 0,
        food_trigger_10 = 0,
        weather_trigger_1 = 1,
        weather_trigger_2 = 0,
        weather_trigger_3 = 0,
        weather_trigger_4 = 0,
        weather_trigger_5 = 1,
        weather_trigger_6 = 0,
        weather_trigger_7 = 1,
        weather_trigger_8 = 1,
        mental_health_trigger_1 = 1,
        mental_health_trigger_2 = 0,
        mental_health_trigger_3 = 1,
        other_trigger_1 = 0,
        other_trigger_2 = 0,
        other_trigger_3 = 0,
        other_trigger_4 = 0
    ),
    ConditionLog(
        date = LocalDateTime.of(2022, 5, 1, 5, 10),
        feeling = ConditionLog.Feeling.feeling_5,
        food_trigger_1 = 1,
        food_trigger_2 = 0,
        food_trigger_3 = 0,
        food_trigger_4 = 1,
        food_trigger_5 = 0,
        food_trigger_6 = 1,
        food_trigger_7 = 1,
        food_trigger_8 = 1,
        food_trigger_9 = 0,
        food_trigger_10 = 0,
        weather_trigger_1 = 1,
        weather_trigger_2 = 0,
        weather_trigger_3 = 0,
        weather_trigger_4 = 0,
        weather_trigger_5 = 1,
        weather_trigger_6 = 0,
        weather_trigger_7 = 1,
        weather_trigger_8 = 1,
        mental_health_trigger_1 = 0,
        mental_health_trigger_2 = 0,
        mental_health_trigger_3 = 0,
        other_trigger_1 = 0,
        other_trigger_2 = 0,
        other_trigger_3 = 0,
        other_trigger_4 = 0
    ),
    ConditionLog(
        date = LocalDateTime.of(2022, 5, 1, 5, 10),
        feeling = ConditionLog.Feeling.feeling_5,
        food_trigger_1 = 1,
        food_trigger_2 = 0,
        food_trigger_3 = 0,
        food_trigger_4 = 1,
        food_trigger_5 = 0,
        food_trigger_6 = 1,
        food_trigger_7 = 1,
        food_trigger_8 = 1,
        food_trigger_9 = 0,
        food_trigger_10 = 0,
        weather_trigger_1 = 1,
        weather_trigger_2 = 0,
        weather_trigger_3 = 0,
        weather_trigger_4 = 0,
        weather_trigger_5 = 1,
        weather_trigger_6 = 0,
        weather_trigger_7 = 1,
        weather_trigger_8 = 1,
        mental_health_trigger_1 = 0,
        mental_health_trigger_2 = 0,
        mental_health_trigger_3 = 0,
        other_trigger_1 = 0,
        other_trigger_2 = 0,
        other_trigger_3 = 0,
        other_trigger_4 = 0
    ),
    ConditionLog(
        date = LocalDateTime.of(2022, 5, 1, 5, 10),
        feeling = ConditionLog.Feeling.feeling_5,
        food_trigger_1 = 1,
        food_trigger_2 = 0,
        food_trigger_3 = 0,
        food_trigger_4 = 1,
        food_trigger_5 = 0,
        food_trigger_6 = 1,
        food_trigger_7 = 1,
        food_trigger_8 = 1,
        food_trigger_9 = 0,
        food_trigger_10 = 0,
        weather_trigger_1 = 1,
        weather_trigger_2 = 0,
        weather_trigger_3 = 0,
        weather_trigger_4 = 0,
        weather_trigger_5 = 1,
        weather_trigger_6 = 0,
        weather_trigger_7 = 1,
        weather_trigger_8 = 1,
        mental_health_trigger_1 = 0,
        mental_health_trigger_2 = 0,
        mental_health_trigger_3 = 0,
        other_trigger_1 = 0,
        other_trigger_2 = 0,
        other_trigger_3 = 0,
        other_trigger_4 = 0
    )
)